version: "3"

services:
    int_host: 
        image: emmame/simple_host
        container_name: int_host
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/int_host:/home
    dmz_host:
        image: emmame/external_host
        container_name: ext_host
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/ext_host:/home
    dmz_service:
        image: emmame/ssh
        container_name: ssh_server
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/ssh_server:/home
    controller:
        image: emmame/ryu
        container_name: controller
        cap_add:
          - NET_ADMIN 
        tty: true
        stdin_open: true
        privileged: true
        volumes:
          - ./configurations/controller:/home

