FROM ubuntu

RUN apt-get update
RUN apt-get install -y net-tools
RUN apt-get install -y iproute2
RUN apt-get install -y iputils-ping
RUN apt-get install -y arp-scan
RUN apt-get install -y nmap
RUN apt-get install -y nano
RUN apt-get install -y ssh && apt-get install -y telnet && apt-get install ftp -y
